// Indicatifs téléphoniques proposés au sélecteur.
// Liste volontairement curée : océan Indien, Afrique, Europe et Amérique du
// Nord — les marchés réels de Haodygasikara. Ajouter une ligne suffit.
// Pas de drapeaux emoji : Windows ne les rend pas, on affiche le code ISO,
// ce qui reste lisible partout et colle mieux à la micro-typo du site.
export const INDICATIFS = [
    { code: "MG", nom: "Madagascar", indicatif: "+261" },

    { code: "AF", nom: "Afrique du Sud", indicatif: "+27" },
    { code: "DZ", nom: "Algérie", indicatif: "+213" },
    { code: "DE", nom: "Allemagne", indicatif: "+49" },
    { code: "AO", nom: "Angola", indicatif: "+244" },
    { code: "SA", nom: "Arabie saoudite", indicatif: "+966" },
    { code: "AR", nom: "Argentine", indicatif: "+54" },
    { code: "AU", nom: "Australie", indicatif: "+61" },
    { code: "AT", nom: "Autriche", indicatif: "+43" },
    { code: "BE", nom: "Belgique", indicatif: "+32" },
    { code: "BJ", nom: "Bénin", indicatif: "+229" },
    { code: "BR", nom: "Brésil", indicatif: "+55" },
    { code: "BF", nom: "Burkina Faso", indicatif: "+226" },
    { code: "CM", nom: "Cameroun", indicatif: "+237" },
    { code: "CA", nom: "Canada", indicatif: "+1" },
    { code: "CN", nom: "Chine", indicatif: "+86" },
    { code: "CY", nom: "Chypre", indicatif: "+357" },
    { code: "KM", nom: "Comores", indicatif: "+269" },
    { code: "CG", nom: "Congo", indicatif: "+242" },
    { code: "CD", nom: "Congo (RDC)", indicatif: "+243" },
    { code: "KR", nom: "Corée du Sud", indicatif: "+82" },
    { code: "CI", nom: "Côte d'Ivoire", indicatif: "+225" },
    { code: "DK", nom: "Danemark", indicatif: "+45" },
    { code: "AE", nom: "Émirats arabes unis", indicatif: "+971" },
    { code: "ES", nom: "Espagne", indicatif: "+34" },
    { code: "US", nom: "États-Unis", indicatif: "+1" },
    { code: "ET", nom: "Éthiopie", indicatif: "+251" },
    { code: "FI", nom: "Finlande", indicatif: "+358" },
    { code: "FR", nom: "France", indicatif: "+33" },
    { code: "GA", nom: "Gabon", indicatif: "+241" },
    { code: "GH", nom: "Ghana", indicatif: "+233" },
    { code: "GR", nom: "Grèce", indicatif: "+30" },
    { code: "GP", nom: "Guadeloupe", indicatif: "+590" },
    { code: "GN", nom: "Guinée", indicatif: "+224" },
    { code: "HU", nom: "Hongrie", indicatif: "+36" },
    { code: "IN", nom: "Inde", indicatif: "+91" },
    { code: "ID", nom: "Indonésie", indicatif: "+62" },
    { code: "IE", nom: "Irlande", indicatif: "+353" },
    { code: "IL", nom: "Israël", indicatif: "+972" },
    { code: "IT", nom: "Italie", indicatif: "+39" },
    { code: "JP", nom: "Japon", indicatif: "+81" },
    { code: "KE", nom: "Kenya", indicatif: "+254" },
    { code: "LU", nom: "Luxembourg", indicatif: "+352" },
    { code: "MW", nom: "Malawi", indicatif: "+265" },
    { code: "MY", nom: "Malaisie", indicatif: "+60" },
    { code: "ML", nom: "Mali", indicatif: "+223" },
    { code: "MA", nom: "Maroc", indicatif: "+212" },
    { code: "MQ", nom: "Martinique", indicatif: "+596" },
    { code: "MU", nom: "Maurice", indicatif: "+230" },
    { code: "MX", nom: "Mexique", indicatif: "+52" },
    { code: "MZ", nom: "Mozambique", indicatif: "+258" },
    { code: "NA", nom: "Namibie", indicatif: "+264" },
    { code: "NG", nom: "Nigéria", indicatif: "+234" },
    { code: "NO", nom: "Norvège", indicatif: "+47" },
    { code: "NZ", nom: "Nouvelle-Zélande", indicatif: "+64" },
    { code: "NL", nom: "Pays-Bas", indicatif: "+31" },
    { code: "PL", nom: "Pologne", indicatif: "+48" },
    { code: "PT", nom: "Portugal", indicatif: "+351" },
    { code: "QA", nom: "Qatar", indicatif: "+974" },
    { code: "RE", nom: "La Réunion", indicatif: "+262" },
    { code: "RO", nom: "Roumanie", indicatif: "+40" },
    { code: "GB", nom: "Royaume-Uni", indicatif: "+44" },
    { code: "RU", nom: "Russie", indicatif: "+7" },
    { code: "RW", nom: "Rwanda", indicatif: "+250" },
    { code: "SN", nom: "Sénégal", indicatif: "+221" },
    { code: "SC", nom: "Seychelles", indicatif: "+248" },
    { code: "SG", nom: "Singapour", indicatif: "+65" },
    { code: "SE", nom: "Suède", indicatif: "+46" },
    { code: "CH", nom: "Suisse", indicatif: "+41" },
    { code: "TZ", nom: "Tanzanie", indicatif: "+255" },
    { code: "TD", nom: "Tchad", indicatif: "+235" },
    { code: "CZ", nom: "Tchéquie", indicatif: "+420" },
    { code: "TH", nom: "Thaïlande", indicatif: "+66" },
    { code: "TG", nom: "Togo", indicatif: "+228" },
    { code: "TN", nom: "Tunisie", indicatif: "+216" },
    { code: "TR", nom: "Turquie", indicatif: "+90" },
    { code: "UG", nom: "Ouganda", indicatif: "+256" },
    { code: "VN", nom: "Viêt Nam", indicatif: "+84" },
    { code: "ZM", nom: "Zambie", indicatif: "+260" },
    { code: "ZW", nom: "Zimbabwe", indicatif: "+263" },
];

export const INDICATIF_DEFAUT = INDICATIFS[0];

export const MOIS = [
    "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
    "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre",
];
